const keyMetricConfig = {
    revenueGrowth: {
        icon: "↗",
        format: "percentage",
        description: "Year-over-year revenue growth",
        meaning: "Shows how quickly revenue increased or decreased compared with the previous period.",
        formula: "(Current revenue - Previous revenue) / Previous revenue x 100"
    },
    netProfitMargin: {
        icon: "%",
        format: "percentage",
        description: "Profit retained from revenue",
        meaning: "Shows how much profit remains from each unit of revenue after tax.",
        formula: "Profit after tax / Revenue from operations x 100"
    },
    ebitdaMargin: {
        icon: "◒",
        format: "percentage",
        description: "Operating profitability",
        meaning: "Shows operating profitability before finance costs, tax, depreciation, and amortisation.",
        formula: "(PBT + Finance costs + Depreciation and amortisation) / Revenue from operations x 100"
    },
    currentRatio: {
        icon: "◫",
        format: "ratio",
        description: "Short-term liquidity",
        meaning: "Shows how many units of current assets are available for each unit of current liabilities.",
        formula: "Total current assets / Total current liabilities"
    },
    debtToEquity: {
        icon: "⇄",
        format: "ratio",
        description: "Financial leverage",
        meaning: "Shows the amount of borrowings supported by each unit of shareholder equity.",
        formula: "Borrowings / Total equity"
    },
    roe: {
        icon: "◎",
        format: "percentage",
        description: "Return generated for shareholders",
        meaning: "Shows the return generated for shareholders using average equity across the two periods.",
        formula: "Profit after tax / Average total equity x 100"
    },
    roa: {
        icon: "▣",
        format: "percentage",
        description: "Return generated from assets",
        meaning: "Shows the return generated by the business using average total assets across the two periods.",
        formula: "Profit after tax / Average total assets x 100"
    }
};

export default keyMetricConfig;
